name: YunnanCoffee
favicon: null
layout_spectrum: 0.50345
typography_spectrum: 0.50864
title: Yunnan Coffee Traders Community
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7702864960301667
  lightness: 0.33416173863224685
  saturation: 0.9764855345711112
  rhythmicContrast: 0.8631054863799363
purpose: []
