name: YunnanCoffee
favicon: null
layout_spectrum: 0.50345
typography_spectrum: 0.50864
title: Yunnan Coffee Traders Community
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#03030b'
    - '#ffefd3'
    - '#364353'
    - '#83988f'
    - '#3c7ba5'
  brandStrength: 0.75
  lightness: 0.5625
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
