name: YunnanCoffee
favicon: null
layout_spectrum: 0.50345
typography_spectrum: 0.50864
title: Yunnan Coffee Traders Community
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2d4ca'
    - '#2c1625'
    - '#a96d53'
    - '#a4bd00'
    - '#d83252'
  brandStrength: 0.6875
  lightness: 0.4375
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
